import type { JobListing } from "./types";

export const DUMMY_JOBS: JobListing[] = [
  {
    _id: "job-hr-manager",
    title: "مدير موارد بشرية",
    code: "UG-726-04",
    sector: "خدمات",
    location: "جدة، السعودية",
    salary: "15,000 - 22,000 ريال",
    education: "بكالوريوس إدارة أعمال",
    experience: "+10 سنوات خبرة",
    jobType: "qualified",
    description:
      "مطلوب فوراً لشركات الأغذية العربية السعودية مدير موارد بشرية ذو خبرة لا تقل عن +10 سنوات في المجال، بشرط الحصول على بكالوريوس إدارة أعمال مع إجادة اللغة الإنجليزية والقدرة على العمل ضمن فريق.",
    requirements: ["بكالوريوس إدارة أعمال", "+10 سنوات خبرة"],
    benefits: ["السكن", "التذاكر", "تذاكر سنوية", "التأمين الطبي الشامل"],
  },
  {
    _id: "job-nurse",
    title: "ممرض عام",
    sector: "صحة",
    location: "الرياض، السعودية",
    salary: "6,000 - 9,000 ريال",
    education: "بكالوريوس تمريض",
    experience: "+3 سنوات خبرة",
    jobType: "qualified",
    description: "مطلوب ممرض عام للعمل في منشأة صحية بالرياض.",
  },
  {
    _id: "job-driver",
    title: "سائق خاص",
    sector: "خدمات منزلية",
    location: "جدة، السعودية",
    salary: "3,000 - 4,500 ريال",
    education: "رخصة قيادة سارية",
    experience: "+2 سنوات خبرة",
    jobType: "unqualified",
    description: "مطلوب سائق خاص للعمل لدى أسرة في جدة.",
  },
  {
    _id: "UG-726-01",
    title: "محاسب مالي",
    sector: "خدمات",
    location: "جدة، المملكة العربية السعودية",
    salary: "تنافسي",
    education: "بكالوريوس تجارة",
    experience: "+5 سنوات خبرة",
    jobType: "qualified",
    description: "مطلوب محاسب مالي لشركات المقاولات في السعودية.",
  },
  {
    _id: "job-sales",
    title: "مندوب مبيعات",
    sector: "خدمات",
    location: "الرياض، السعودية",
    salary: "4,000 - 6,000 ريال",
    education: "ثانوية عامة",
    experience: "+1 سنة خبرة",
    jobType: "unqualified",
    description: "مطلوب مندوب مبيعات للعمل في الرياض.",
  },
  {
    _id: "job-civil",
    title: "مهندس مدني",
    sector: "خدمات",
    location: "الدمام، السعودية",
    salary: "12,000 - 18,000 ريال",
    education: "بكالوريوس هندسة",
    experience: "+7 سنوات خبرة",
    jobType: "qualified",
    description: "مطلوب مهندس مدني بخبرة في المشاريع الإنشائية.",
  },
  {
    _id: "job-tech",
    title: "فني صيانة",
    sector: "خدمات",
    location: "الرياض، السعودية",
    salary: "3,500 - 5,500 ريال",
    education: "دبلوم فني",
    experience: "+2 سنوات خبرة",
    jobType: "unqualified",
    description: "مطلوب فني صيانة للعمل في الرياض.",
  },
  {
    _id: "job-pediatric-nurse",
    title: "ممرضة أطفال",
    sector: "صحة",
    location: "جدة، السعودية",
    salary: "5,500 - 8,000 ريال",
    education: "بكالوريوس تمريض",
    experience: "+4 سنوات خبرة",
    jobType: "qualified",
    description: "مطلوب ممرضة أطفال للعمل في جدة.",
  },
  {
    _id: "job-cook",
    title: "طباخ",
    sector: "خدمات منزلية",
    location: "الرياض، السعودية",
    salary: "3,000 - 5,000 ريال",
    education: "خبرة عملية",
    experience: "+3 سنوات خبرة",
    jobType: "unqualified",
    description: "مطلوب طباخ للعمل في منزل بالرياض.",
  },
];
